# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "nixfmt"
options = ["-w 120", "-v"]
includes = ["*.nix"]
excludes = ["*.yaml", "*.yml", "*.json", "*.md", ".github/**"]

[formatter.yaml]
command = "yamlfmt"
options = [""]
includes = ["*.yaml", "*.yml"]
excludes = ["*.nix", "*.json", "*.md", ".github/**"]

[formatter.json]
command = "jsonfmt"
options = ["-w"]
includes = ["*.json"]
excludes = ["*.nix", "*.yaml", "*.yml", "*.md", ".github/**"]

# [formatter.md]
# command  = "markdownlint"
# options  = [ "--disable", "MD013", "MD033", "--", "--fix"]
# includes = [ "*.md" ]
# excludes = []
